# Version of Docker-compose
version: "3.8"
services:
  # Service name
  node:
    # Creating a custom image
    build:
      # Location to the Dockerfile
      context: .
      # Name of the Dockerfile
      dockerfile: Dockerfile
    ports:
      # External port:Internal port
      - 8000:8000
